#!/usr/bin/env python3
"""Bounding box of every part on the board (from KiCad's VRML export), as an OpenSCAD include for the
interference checks against the printed / bought mechanical parts.

    python3 board_boxes.py board.wrl out.scad
The VRML must be exported with --units mm --user-origin 100x50mm (export_assembly.sh does that).
Output in OpenSCAD / board coordinates: x right, y to the rear, z = 0 on the PCB top.
"""
import sys

import asm3d


def boxes(wrl):
    p = asm3d._Parser(asm3d._tokens(open(wrl).read()))
    roots = []
    while p.peek() is not None:
        roots.append(p.node())
    top = roots[0]
    m0 = asm3d._transform_matrix(top["f"])
    out = []

    def collect(n, m, pts):
        if n["type"] in ("Transform", "Group"):
            mm = asm3d._mat_mul(m, asm3d._transform_matrix(n["f"])) if n["type"] == "Transform" else m
            for c in n["f"].get("children", []):
                collect(c, mm, pts)
        elif n["type"] == "Shape":
            g = n["f"].get("geometry")
            if g and g["type"] == "IndexedFaceSet":
                q = g["f"]["coord"]["f"]["point"]
                for k in range(0, len(q) - 2, 3):
                    x, y, z = q[k], q[k + 1], q[k + 2]
                    pts.append(tuple(m[i][0] * x + m[i][1] * y + m[i][2] * z + m[i][3] for i in range(3)))

    for k in top["f"].get("children", []):
        pts = []
        collect(k, m0, pts)
        if not pts:
            continue
        lo = [min(q[j] for q in pts) for j in range(3)]
        hi = [max(q[j] for q in pts) for j in range(3)]
        if hi[0] - lo[0] > 50 or hi[2] - lo[2] < 0.2:   # board body, copper, mask, silk layers
            continue
        # KiCad 3D (y front, PCB centred on z = 0) -> board coordinates (y rear, PCB top z = 0)
        out.append(((lo[0], -hi[1], lo[2] - 0.8), (hi[0], -lo[1], hi[2] - 0.8)))
    return out


if __name__ == "__main__":
    bb = boxes(sys.argv[1])
    with open(sys.argv[2], "w") as f:
        f.write("// generated by scripts/board_boxes.py: bounding boxes of the parts on the Lite board\n")
        f.write("BOARD_BOXES = [\n")
        f.write(",\n".join("  [[%.2f, %.2f, %.2f], [%.2f, %.2f, %.2f]]" % (a + b) for a, b in bb))
        f.write("\n];\nmodule board_parts(g = 0) for (b = BOARD_BOXES) translate(b[0] - [g, g, g]) cube(b[1] - b[0] + [2 * g, 2 * g, 2 * g]);\n")
    print("%d parts -> %s" % (len(bb), sys.argv[2]))
